{
  "hash": "ef8ac776b9f49d842776542b4f42bdf2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R Code Tutorials\"\ncode-annotations: hover\n---\n\nThe below tutorials are all focused on neat features of the R programming language. See sub-headings for more specifics!\n\n## Class Coercion\n\nThe R programming language is extremely useful for a variety of data science tasks. It--and other object-oriented programming languages--allow storing values in \"objects\" and then using those objects to re-call and use the values to which they are bound. In order to combine different \"types\" of values, R has to \"coerce\" one or both of the values into a shared type (sometimes a.k.a. \"class\" depending on what you're working on).\n\n### Coercion Rules\n\n**The order of this coercion is logical {{< fa arrow-right >}} integer {{< fa arrow-right >}} double {{< fa arrow-right >}} character**. Logicals are the most specific type of atomic vector and the order proceeds to characters which are the most general type. It might be helpful to consider some examples. Let's begin by making one object for each atomic type (identified above).\n\n:::{.panel-tabset}\n#### Logical\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_logi <- c(TRUE, FALSE)\ntypeof(x = my_logi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"logical\"\n```\n\n\n:::\n:::\n\n\n#### Integer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_int <- c(4L, 5L, 6L) # <1>\ntypeof(x = my_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n1. The `L` at the end is for \"length\" and ensures that number is type \n\n#### Double\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_doub <- c(3.14, 77.0, 20) # <2>\ntypeof(x = my_doub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n:::\n\n2. Even though \"20\" _looks_ like an integer, R will consider it a double without the trailing `L`\n\n#### Character\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_char <- c(\"a\", \"b\", \"c\")\ntypeof(x = my_char)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n:::\n\nNow that we have those, let's combine them in sequence so we can see the coercion rules in action!\n\n:::{.panel-tabset}\n#### Logical + Integer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_logi.int <- c(my_logi, my_int)\nmy_logi.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 0 4 5 6\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_logi.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n\n#### Integer + Double\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_int.doub <- c(my_int, my_doub)\nmy_int.doub\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  4.00  5.00  6.00  3.14 77.00 20.00\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_int.doub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n:::\n\n\n#### Double + Character\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_doub.char <- c(my_doub, my_char)\nmy_doub.char\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"3.14\" \"77\"   \"20\"   \"a\"    \"b\"    \"c\"   \n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_doub.char)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n:::\n\n### Other Coercion Variants\n\nYou may have noticed that the above examples are missing some classes of object with which you may work regularly. These were absent from the above examples because the first component of this tip is restricted only to \"type\" coercion while you may be thinking of \"class\" coercion. See below for some examples that may address what felt missing above.\n\n:::{.panel-tabset}\n#### Numeric Coercion\n\n<u>\"Numeric\" values are technically inclusive of both integers and doubles</u>. The reason to avoid that phrasing earlier was just to be more precise about the coercion rules between integers and doubles.\n\n#### Factor Coercion\n\n<u>Factors are a special case of an integer</u>. This does mean that coercing a factor can have surprising results in some cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make our character object into a factor\nmy_fact <- as.factor(x = my_char)\nmy_fact\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] a b c\nLevels: a b c\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the type & class\ntypeof(x = my_fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"factor\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Coerce it by combining with a double\nmy_doub.fact <- c(my_doub, my_fact)\nmy_doub.fact # <3>\ntypeof(x = my_doub.fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  3.14 77.00 20.00  1.00  2.00  3.00\n[1] \"double\"\n```\n\n\n:::\n:::\n\n3. Because doubles \"win\" coercion against integers, our `a`, `b`, and `c` become `1.00`, `2.00`, and `3.00` respectively!\n\n#### Date Coercion\n\n<u>Dates are a special case of a double</u>. They represent the number of **days** since January 1^st^, 1970. Like factors, this means that coercion can behave in a way that surprises you.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a date\nmy_date <- as.Date(x = \"2024-10-13\")\n\n# Check the type & class\ntypeof(x = my_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coerce it by combining with a character\nmy_char.date <- c(my_char, my_date)\nmy_char.date\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\"     \"b\"     \"c\"     \"20009\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_char.date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n#### Date-Time Coercion\n\n<u>Date-times are a special case of a double</u>. They represent the number of **seconds** since January 1^st^, 1970. Just like dates, this can make coercion surprising here as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a datetime\nmy_datetime <- as.POSIXct(\"2024-10-13 23:00\", tz = \"UTC\")\n\n# Check the type & class\ntypeof(x = my_datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"POSIXct\" \"POSIXt\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# Coerce it by combining with a character\nmy_char.datetime <- c(my_char, my_datetime)\nmy_char.datetime\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\"          \"b\"          \"c\"          \"1728860400\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_char.datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n:::\n\n\n## Signaling Conditions\n\nMany programming languages rely on being able to signal \"conditions\" when code doesn't work as intended. These conditions range from effectively 'for your information' notes all the way to full-blown errors. See the tabs below for the three most common conditions in R\n\n:::{.panel-tabset}\n### Message\n\n<u>Messages indicate that an action has been taken on the user's behalf but not necessarily a problem</u>. These can be useful to explicitly inform a user about an assumed default value or--for code that iterates for a long time--reassure users that the function is still working.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmessage(\"Pssst\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPssst\n```\n\n\n:::\n:::\n\n\n### Warning\n\n<u>Warnings indicate that something has gone wrong but the function could at least partially recover</u>. These can be useful when some facet of a user's input is incorrect but the code can still complete. I often uses warnings in my custom functions that have at least one argument that expects a logical (i.e., `T` or `F`). If the user supplies anything other than a logical, I return a warning and coerce that argument to whatever default logical I originally defined.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwarning(\"Oops\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Oops\n```\n\n\n:::\n:::\n\n\n### Error\n\n<u>Errors indicate that that the function _cannot_ continue and execution must stop</u>. Including custom input checks with informative messages in an important facet of package development! And in non-function code, error messages are your first indicating that something is not working as it should.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstop(\"Oh no\")\n#> Error: Oh no  # <1>\n```\n:::\n\n1. I included what this looks like as a commented-out line because otherwise the website can't render this page.\n\n:::\n\n## Looping Across Integers\n\nWhen iterating a given operation it is common to loop across some integer. For example, maybe you're looping across a list and want to use the numeric position of each element of the list. Typically, this is accomplished like so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define vector\nmy_vec <- c(\"a\", \"b\", \"c\")\n\n# Loop across it\nfor(k in 1:length(my_vec)){\n  \n  # Print the kth letter\n  cat(\"Processing \", my_vec[[k]], \"\\n\", sep=\"\")\n  \n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing a\nProcessing b\nProcessing c\n```\n\n\n:::\n:::\n\n\nThis works in this case but <u>if the vector of values has _no_ elements, the loop will behave unexpectedly</u>. This is because `1:length` of an empty vector returns `1` and `0`! Let's demonstrate this here:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make an empty vector\nempty_vec <- c()\n\n# Loop across it\nfor(k in 1:length(empty_vec)){\n  \n  # Print the kth letter\n  cat(\"Processing \", empty_vec[[k]], \"\\n\", sep=\"\")\n  \n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nProcessing \nProcessing \n```\n\n\n:::\n\n```{.r .cell-code}\n# Demonstrate how the loop interpreted the `1:length` bit\n1:length(empty_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 0\n```\n\n\n:::\n:::\n\n\nSee how the loop still appears to work but isn't returning values that might be expected? This can be especially challenging to debug with a more complex (i.e., more realistic) loop. However, we can reformat the first part of the loop to use `seq_along` instead of `1:length`. The loop will still not work but it will be more clear that the issue is with your initial vector of inputs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Loop across the empty vector\nfor(k in seq_along(empty_vec)){ # <1>\n  \n  # Print the kth letter\n  cat(\"Processing \", empty_vec[[k]], \"\\n\", sep=\"\")\n  \n}\n\n# Demonstrate how the loop interpreted the `seq_along` bit\nseq_along(empty_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ninteger(0)\n```\n\n\n:::\n:::\n\n1. Technically, `seq_along` has an `along.with` argument but for conciseness I've let it be implicit in this demo\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}